### ISSUE TITLE
Feature: allow to dismiss the popup when the backdrop is clicked

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/ax-popup-widget#12]
Currently there seem to be 3 ways to dismiss a popup:
1. click the "x" (in case the `closeIcon` feature is enabled)
2. press the escape key
3. fire a `takeActionRequest` with one of the actions in `features.close.onActions`

… can we add a fourth option, to dismiss the popup when the backdrop is clicked? The bahavior should be exactly the same as when the escape key is pressed.

**Comment by jonaswjs** [comment]
Implemented on `master` (`v2.3.0`).
