### ISSUE TITLE
visibility flag: do not publish unless configured

### ISSUE THREAD

**Issue by x1B** [LaxarJS/ax-popup-widget#16]
The popup widget publishes a flag on visibility change even when no flag was configured.

This can lead to confusing behavior, especially if there are multiple popups on a page.

To fix this, it would probably be enough to remove the default values in the widget.json, and possibly add some null-handling.

However, this might break applications, so it's a major bump.

**Comment by jonaswjs** [comment]
Implemented on master (v3.0.0)

### Breaking Change

The popup widget does not have a default property for the visibility flag anymore. Thus it does not publish the visibility flag unless it is configured. The widget in versions less than 3.0.0 publishes the flag with the topic `visible-popup` even when `features.visibility.flag` was not configured. To keep the old behavior after an upgrade add the flag to your page configurations.

Old configuration:

```
{
   "widget": "laxarjs/ax-popup-widget",
   "id": "myPopup",
   "features": {
      "content": {
         "layout": "popup-layout"
      }
   }
}
```

New configuration _only if needed_:

```
{
   "widget": "laxarjs/ax-popup-widget",
   "id": "myPopup",
   "features": {
      "content": {
         "layout": "popup-layout"
      },
      "visibility": {
         "flag": "visible-popup"
      }
   }
}
```
